### PR TITLE
Add croatian transaltion

### PR DESCRIPTION
**Pull request by muzena**

### CODE REVIEW

**Comment by jlHertel** [comment]
Thanks for the pull-request

**Comment by jlHertel** [comment]
Please note that your translation will only affect the DRI Configurator itself.
The options and their descriptions come directly from Mesa, so if you want a full translated software you will also need to add this translation to mesa.

**Comment by muzena** [comment]
@jlHertel 
Where can I add translation to mesa?

**Comment by jlHertel** [comment]
@muzena I think the [mesa git](https://cgit.freedesktop.org/mesa/mesa/tree/) is a good starting point
What you are looking is under src/mesa/drivers/dri/common/xmlpool/

**Comment by jlHertel** [comment]
@muzena Yes you are right.
It seems I have a very old copy of mesa at my disk :)

Thanks for pointing this out.

**Pull request merged**
